function [rdPower, rangeAxis, dopplerHz] = anchoredRangeDopplerFFT( ...
        newestFirstCSI, carrierOffsetsHz, subcarrierSpacing, ...
        rangeFftLength, dopplerFftLength, samplePeriod)
%ANCHOREDRANGEDOPPLERFFT Delay IFFT and chronological slow-time FFT.
%   Map measured CRS to their actual OFDM bins before the range IFFT. This
%   preserves the missing DC bin instead of treating the CRS grid as exactly
%   uniform across DC. Unmeasured bins are zero-filled, not interpolated.
%   All ranges refer to the current anchor. Axes use the monostatic c/2
%   convention (a bistatic recording measures equivalent path length/rate).
    validateattributes(newestFirstCSI, {'numeric'}, ...
        {'2d', 'finite', 'nonempty'});
    validateattributes(subcarrierSpacing, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
    validateattributes(samplePeriod, {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'});
    validateattributes(rangeFftLength, {'numeric'}, ...
        {'scalar', 'integer', '>=', 2});
    validateattributes(dopplerFftLength, {'numeric'}, ...
        {'scalar', 'integer', '>=', size(newestFirstCSI, 2)});
    offsets = double(carrierOffsetsHz(:));
    assert(numel(offsets) == size(newestFirstCSI, 1) && ...
        all(isfinite(offsets)) && isreal(offsets), ...
        'anchoredRangeDopplerFFT:Carriers', 'Invalid carrier frequency offsets.');
    bins = round(offsets/subcarrierSpacing);
    assert(all(abs(offsets/subcarrierSpacing-bins) < 1e-6), ...
        'anchoredRangeDopplerFFT:Grid', 'Carriers must lie on the OFDM grid.');
    fftRows = mod(bins, rangeFftLength)+1;
    assert(numel(unique(fftRows)) == numel(fftRows), ...
        'anchoredRangeDopplerFFT:Aliasing', 'Range FFT aliases measured carriers.');
    rangeWindow = hamming(numel(offsets));
    timeWindow = hann(size(newestFirstCSI, 2), 'periodic').';
    % Reversing newest-first columns is essential for the Doppler sign.
    dopplerCSI = fftshift(fft(fliplr(newestFirstCSI) .* timeWindow, ...
        dopplerFftLength, 2), 2);
    frequencyGrid = complex(zeros(rangeFftLength, dopplerFftLength));
    frequencyGrid(fftRows, :) = dopplerCSI .* rangeWindow;
    rdComplex = fftshift(ifft(frequencyGrid, [], 1), 1) ...
        * rangeFftLength / (sum(rangeWindow)*sum(timeWindow));
    rdPower = abs(rdComplex).^2;
    rangeAxis = (-floor(rangeFftLength/2):ceil(rangeFftLength/2)-1) ...
        * (299792458/(2*subcarrierSpacing*rangeFftLength));
    dopplerHz = (-floor(dopplerFftLength/2):ceil(dopplerFftLength/2)-1) ...
        / (dopplerFftLength*samplePeriod);
end
