function config = defaultLteSenseConfig()
%DEFAULTLTESENSECONFIG Default configuration for the modular LTE sensor.

config = struct();

config.Acquisition = struct( ...
    'HeadStartSample0', 307200*10, ...
    'SearchDurationSeconds', 0.05, ...
    'InitialNDLRB', 6, ...
    'MaxCellCount', 2, ...
    'SSSDetection', 'PostFFT');

config.Tracking = struct( ...
    'CpFraction', 0.55, ...
    'MaximumTxPorts', 2, ...
    'ReceiveAntennaIndices', 1, ...
    'CfoCpGuardSamples', 20, ...
    'CfoCpStartSample', 10, ...
    'StaticFilterOrder', 4, ...
    'StaticFilterCutoff', pi/512);

config.Sync = struct( ...
    'EnableMonitoring', true, ...
    'CheckIntervalFrames', 10, ...
    'SuspectThreshold', 0.20, ...
    'LostThreshold', 0.10, ...
    'ConsecutiveFailures', 3);

config.Cancellation = struct( ...
    'Method', 'passthrough', ...
    'WarmupPolicy', 'bypass', ...
    'ArOrder', 5, ...
    'WarmupFrames', 40, ...
    'SketchSize', 32, ...
    'CorrelationForgetting', 0.98, ...
    'CorrelationUpdatePeriod', 1, ...
    'RootUpdatePeriod', 8, ...
    'DiagonalLoading', 1e-4, ...
    'MinimumYuleWalkerRcond', 1e-5, ...
    'KalmanProcessNoiseRatio', 1e-3, ...
    'KalmanMeasurementForgetting', 0.98, ...
    'KalmanInitialCovarianceRatio', 1, ...
    'KalmanMinimumVarianceRatio', 1e-4, ...
    'KalmanMaximumVarianceRatio', 10, ...
    'KalmanPosteriorCancellationFraction', 0, ...
    'CoherenceLow', 0.10, ...
    'CoherenceHigh', 0.60, ...
    'CoherenceForgetting', 0.90, ...
    'MaximumCancellation', 0.92, ...
    'PredictionPowerLimit', 2.0, ...
    'FramePeriodSeconds', 10e-3, ...
    'SpectrumPoleRadius', 0.995, ...
    'SpectrumGridSize', 4096);

config.RangeDoppler = struct( ...
    'WindowFrames', 10, ...
    'HopFrames', 10, ...
    'Group', 'G1', ...
    'ReceiveAntenna', 1, ...
    'TransmitAntenna', 1, ...
    'NoiseFloorQuantile', 0.10, ...
    'DisplayBelowNoiseDb', 10, ...
    'DisplayAboveNoiseDb', 40, ...
    'RequireCancellationReady', false);

config.Display = struct( ...
    'Enabled', true, ...
    'FigureVisible', 'on', ...
    'Colormap', 'jet');
config.Display.Views = struct( ...
    'RangeDoppler', struct( ...
        'WindowKey', 'live-monitor', ...
        'WindowName', 'LTE Sensing Monitor', ...
        'GridSize', [1, 2], ...
        'AxesKey', 'range-doppler', ...
        'Tile', 1), ...
    'ArSpectrum', struct( ...
        'WindowKey', 'live-monitor', ...
        'WindowName', 'LTE Sensing Monitor', ...
        'GridSize', [1, 2], ...
        'AxesKey', 'ar-interference-spectrum', ...
        'Tile', 2));

config.Execution = struct( ...
    'MaximumSubframes', Inf, ...
    'Verbose', true);
end
